// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgzghlsqimujcltukewk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnemdobHNxaW11amNsdHVrZXdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3NzI4NjgsImV4cCI6MjA1NzM0ODg2OH0.4DoyEEqJhbZmdD-bAxfW8M7g0rIyJow3pFe0XP1QlzA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);